_base_: '../_base_/ade20k.yml'

batch_size: 4  # total is 16
iters: 160000

optimizer:
  weight_decay: 5.0e-4

lr_scheduler:
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5
  learning_rate: 0.01

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

model:
  type: LRASPP
  backbone:
    type: MobileNetV3_large_x1_0_os8  # out channels: [24, 40, 112, 160]
    pretrained: https://paddleseg.bj.bcebos.com/dygraph/backbone/mobilenetv3_large_x1_0_ssld.tar.gz
  backbone_indices: [0, 1, 3]
  lraspp_head_inter_chs: [32, 64]
  lraspp_head_out_ch: 128
  resize_mode: bilinear
  use_gap: True