batch_size: 8   # 4 gpu
iters: 100000
save_interval: 1000

train_roots:
  - data/portrait14k
  - data/matting_human_half
  - data/humanseg

train_data_ratio:
  - 8
  - 1
  - 1

val_roots:
  - data/portrait14k
  - data/matting_human_half
  - data/humanseg

dataset_weights:
  - 0.6
  - 0.4
  - 0

class_weights:
  - 0.5
  - 0.5

train_transforms:
  - type: PaddingByAspectRatio
    aspect_ratio: 1.77777778
  - type: Resize
    target_size: [398, 224]
  - type: ResizeStepScaling
    scale_step_size: 0
  - type: RandomRotation
  - type: RandomPaddingCrop
    crop_size: [398, 224]
  - type: RandomHorizontalFlip
  - type: RandomDistort
  - type: RandomBlur
    prob: 0.3
  - type: Normalize

val_transforms:
  - type: PaddingByAspectRatio
    aspect_ratio: 1.77777778
  - type: Resize
    target_size: [398, 224]
  - type: Normalize

export:
  transforms:
    - type: Resize
      target_size: [398, 224]
    - type: Normalize

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1, 1, 1, 1]

model:
  type: PPLiteSeg
  num_classes: 2
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
  backbone_indices: [1, 2, 3, 4]
  cm_out_ch: 128
  arm_out_chs: [8, 32, 64, 128]
  seg_head_inter_chs: [4, 16, 32, 64]