batch_size: 8    # 4 GPUs
iters: 50000
save_interval: 1000

train_roots:
  - data/portrait14k
  - data/maadaa

train_data_ratio:
  - 2
  - 1

val_roots:
  - data/portrait14k
  - data/maadaa

dataset_weights:
  - 0.5
  - 0.5

class_weights:
  - 0.5
  - 0.5

train_transforms:
  - type: PaddingByAspectRatio
    aspect_ratio: 1.77777778
  - type: Resize
    target_size: [320, 180]
  - type: ResizeStepScaling
    scale_step_size: 0
  - type: RandomRotation90
  - type: RandomRotation
    max_rotation: 30
  - type: RandomPaddingCrop
    crop_size: [320, 180]
  - type: RandomHorizontalFlip
  - type: RandomDistort
  - type: RandomBlur
    prob: 0.3
  - type: Normalize

val_transforms:
  - type: PaddingByAspectRatio
    aspect_ratio: 1.77777778
  - type: Resize
    target_size: [320, 180]
  - type: Normalize

export:
  transforms:
    - type: Resize
      target_size: [320, 180]
    - type: Normalize

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.001
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: LovaszSoftmaxLoss
      coef: [0.8, 0.2]
  coef: [1, 1, 1]

model:
  type: MobileSeg
  num_classes: 2
  backbone:
    type: MobileNetV3_large_x1_0  # out channels: [24, 40, 112, 160]
    pretrained: https://paddleseg.bj.bcebos.com/dygraph/backbone/mobilenetv3_large_x1_0_ssld.tar.gz
  cm_bin_sizes: [1, 2]
  cm_out_ch: 64
  arm_out_chs: [32, 48, 64]
  seg_head_inter_chs: [16, 32, 32]
  pretrained: output/mixed_dataset_mobileseg_mobilenetv3/test_1/best_model/model.pdparams
