_base_: '../_base_/deepglobe.yml'

batch_size: 4  # total: 4*4
iters: 80000   # 8w * 16 / 6226 = 205 epoch

model:
  type: OCRNet
  backbone:
    type: HRNet_W48
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
  backbone_indices: [0]

loss:
  types:
    - type: DiceLoss
    - type: DiceLoss
  coef: [1, 0.4]
