_base_: '../_base_/deepglobe.yml'

batch_size: 4  # total: 4*4
iters: 80000  # 8w * 16 / 6226 = 205 epoch

model:
  type: PPLiteSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 64]

loss:
  types:
    - type: DiceLoss
  coef: [1, 1, 1]
