_base_: 'lvjian1_512x512.yml'

batch_size: 4  # total: 4*4
iters: 80000   # 2w * 16 / 1.2w = 26 epoch   12647

model:
  type: OCRNet
  backbone:
    type: HRNet_W18
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  backbone_indices: [0]

loss:
  types:
    #- type: CrossEntropyLoss
    #- type: OhemCrossEntropyLoss
    #  min_kept: 65000   # batch_size * w * h // 16
    #- type: FocalLoss
    #  alpha: 0.9
  coef: [1, 0.4]
