_base_: './defect.yml'


batch_size: 16
iters: 80000

model:
  type: PPLiteSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 65000
    - type: OhemCrossEntropyLoss
      min_kept: 65000
    - type: OhemCrossEntropyLoss
      min_kept: 65000
  coef: [1, 1, 1]